// Writes dist/slides.ts: one entry per talks/<slug>/ directory that has
// a built public/slides/<slug>/manifest.json (the peitho build output,
// whose `title` comes from the deck itself). components/SlidesIndex.tsx
// imports SLIDES from here instead of listing talks by hand — add a talk
// by running `peitho build talks/<slug>/deck.md --out public/slides/<slug>`
// and dropping talks/<slug>/talk.json, not by editing that file.
//
// A talks/<slug>/ without a built manifest.json yet is silently skipped —
// building is what "publishes" a talk. But once it's built, a missing or
// unparsable talk.json fails the build loudly instead of quietly dropping
// the talk from the list — talk.json is easy to forget since peitho's own
// `deck.md` frontmatter has a fixed key set and can't carry a `date`.
//
// Runs before `vite build` in the dev/build/deploy scripts.

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const talksDir = 'talks'
const slugs = readdirSync(talksDir).filter((f) => statSync(join(talksDir, f)).isDirectory())

const slides = slugs
  .map((slug) => {
    const manifestPath = join('public', 'slides', slug, 'manifest.json')
    if (!existsSync(manifestPath)) return null

    const talkJsonPath = join(talksDir, slug, 'talk.json')
    if (!existsSync(talkJsonPath)) {
      throw new Error(
        `talks/${slug}/ is built (public/slides/${slug}/manifest.json exists) but has no talk.json.\n` +
          `  Create it: echo '{ "date": "YYYY-MM-DD" }' > talks/${slug}/talk.json`,
      )
    }
    const { date } = JSON.parse(readFileSync(talkJsonPath, 'utf-8'))
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date ?? '')) {
      throw new Error(`talks/${slug}/talk.json: "date" must be YYYY-MM-DD, got ${JSON.stringify(date)}`)
    }

    const { title } = JSON.parse(readFileSync(manifestPath, 'utf-8'))
    return { slug, date, title }
  })
  .filter((t) => t !== null)
  .sort((a, b) => b.date.localeCompare(a.date))

mkdirSync('dist', { recursive: true })
writeFileSync(
  join('dist', 'slides.ts'),
  `// Code generated by scripts/generate-slides.mjs. DO NOT EDIT.\nexport const SLIDES = ${JSON.stringify(slides, null, 2)} as const\n`,
)
console.log(`Generated: dist/slides.ts (${slides.length} talk(s), ${slugs.length - slides.length} unbuilt)`)
