// Writes dist/blog-posts.ts and dist/diary-posts.ts: a static import per
// content/<section>/*.md file whose frontmatter has `published: true`,
// keyed by filename (minus .md) as the slug. blog/content.ts and
// diary/content.ts import RAW_POSTS from these instead of listing posts
// by hand — drop a file with `published: true` and it shows up on the
// next build. Files without that line are left out (drafts), unless
// this runs with --dev (the `dev` npm script), in which case every file
// is included so drafts are visible locally before they're published.
//
// Runs before `vite build` in the dev/build/deploy scripts.

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'

const PUBLISHED = /^published:\s*true\s*$/m
const includeDrafts = process.argv.includes('--dev')

function generate(section) {
  const dir = join('content', section)
  const files = readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort()
  const published = includeDrafts ? files : files.filter((f) => PUBLISHED.test(readFileSync(join(dir, f), 'utf-8')))

  const imports = published
    .map((f, i) => `import post${i} from '../content/${section}/${f}'`)
    .join('\n')
  const entries = published
    .map((f, i) => `  '${basename(f, '.md')}': post${i},`)
    .join('\n')

  mkdirSync('dist', { recursive: true })
  writeFileSync(
    join('dist', `${section}-posts.ts`),
    `// Code generated by scripts/generate-posts.mjs. DO NOT EDIT.\n${imports}\n\nexport const RAW_POSTS: Record<string, string> = {\n${entries}\n}\n`,
  )
  console.log(
    includeDrafts
      ? `Generated: dist/${section}-posts.ts (${published.length} total, drafts included — --dev)`
      : `Generated: dist/${section}-posts.ts (${published.length} published, ${files.length - published.length} draft)`,
  )
}

generate('blog')
generate('diary')
